[package]
name = "studio-github"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
studio-net = { path = "../studio-net" }
studio-security = { path = "../studio-security" }
thiserror.workspace = true

[lints]
workspace = true
