//! The deterministic Studio IR → AssemblyScript lowering backend.
//!
//! [`emit`] renders one static guest module in the exact conventions of the
//! existing hand-written examples (`examples/starter`, `examples/pos-desktop`):
//! a `studio_init` export that emits a v1 protocol `mount` payload, and a
//! `studio_event` export that dispatches typed navigation actions.  The
//! emitted text is a pure function of the IR, so identical input produces
//! byte-identical output.
//!
//! Compilation from generated AssemblyScript to Wasm intentionally reuses the
//! example build machinery (`asc` + `asconfig.json`); this crate does not
//! invoke any compiler itself.
//!
//! # Intentionally non-deterministic seams
//!
//! None inside this crate.  Byte-for-byte determinism ends at the ASC toolchain
//! boundary, which is owned by the example/package build configuration.
//!
//! # Debug oracle
//!
//! [`simulate_event`] mirrors the dispatch the emitter generates, in pure Rust,
//! so tests can compare observable mount/navigate behavior against a
//! hand-written counterpart without executing Wasm.

use std::collections::BTreeMap;

use studio_protocol::{GuestMessage, HostEvent, MountTree, NavigationCommand, NodeKind, PROTOCOL_VERSION, UiNode};
use serde_json::Value;

use crate::ir::{IrNavigationOperation, IrProperty, IrNode, StudioIrModule};

/// The artifacts of one lowering: generated AssemblyScript plus the mount
/// payload it embeds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmittedModule {
    /// Generated AssemblyScript source text.
    pub assembly_source: String,
    /// The v1 protocol `mount` payload emitted by `studio_init`.
    pub mount_payload: String,
}

/// Emit deterministic AssemblyScript for a lowered module.
///
/// The first screen is mounted at startup; every navigation action becomes one
/// branch of the generated `studio_event` dispatch, in authored order.
#[must_use]
pub fn emit(module: &StudioIrModule) -> EmittedModule {
    let mount_payload = mount_payload(module);
    let mut source = String::new();
    source.push_str("// Generated by studio-script::assemblyscript. DO NOT EDIT.\n");
    source.push_str(&format!(
        "// Studio IR version {}; {} screen(s); {} navigation action(s).\n",
        module.version,
        module.screens.len(),
        module.actions.len()
    ));
    source.push_str("\nconst MOUNT_PAYLOAD: string = \"");
    source.push_str(&escape_as_string(&mount_payload));
    source.push_str("\";\n\n");

    source.push_str("@external(\"studio_host\", \"emit\")\n");
    source.push_str("declare function hostEmit(pointer: i32, length: i32): i32;\n\n");

    source.push_str("function emit(message: string): i32 {\n");
    source.push_str("  const bytes = String.UTF8.encode(message, false);\n");
    source.push_str("  return hostEmit(changetype<i32>(bytes), bytes.byteLength);\n");
    source.push_str("}\n\n");

    source.push_str("export function studio_alloc(length: i32): i32 {\n");
    source.push_str("  return length <= 65536 ? 32768 : 0;\n");
    source.push_str("}\n\n");
    source.push_str("export function studio_dealloc(_pointer: i32, _length: i32): void {}\n\n");

    source.push_str("export function studio_init(_pointer: i32, _length: i32): i32 {\n");
    source.push_str("  return emit(MOUNT_PAYLOAD);\n");
    source.push_str("}\n\n");

    source.push_str("export function studio_event(pointer: i32, length: i32): i32 {\n");
    source.push_str("  const event = String.UTF8.decodeUnsafe(pointer, length, false);\n");
    for action in &module.actions {
        let trigger = format!(
            "\"node_id\":\"{}\"",
            escape_json(&action.trigger_node_id)
        );
        let event_match = format!("\"event\":\"{}\"", action.trigger_event.as_str());
        source.push_str(&format!(
            "  if (event.includes(\"{}\") && event.includes(\"{}\")) {{\n",
            escape_as_string(&trigger),
            escape_as_string(&event_match)
        ));
        source.push_str("    return emit(\"");
        source.push_str(&escape_as_string(&navigate_message(&action.operation)));
        source.push_str("\");\n");
        source.push_str("  }\n");
    }
    source.push_str("  return 0;\n");
    source.push_str("}\n");

    EmittedModule {
        assembly_source: source,
        mount_payload,
    }
}

/// Mirror the generated `studio_event` dispatch in pure Rust.
///
/// Given a serialized [`HostEvent`] envelope, returns the serialized
/// [`GuestMessage`] the emitted module would respond with, or [`None`] when no
/// generated branch matches.
///
/// # Errors
///
/// Returns an error message when `event_json` is not a valid host UI event.
pub fn simulate_event(
    module: &StudioIrModule,
    event_json: &str,
) -> Result<Option<String>, String> {
    let Ok(HostEvent::Ui(event)) = serde_json::from_str::<HostEvent>(event_json) else {
        return Err("event_json is not a serialized host UI event".to_owned());
    };
    for action in &module.actions {
        if action.trigger_node_id == event.node_id
            && action.trigger_event.as_str() == event.event
        {
            return Ok(Some(navigate_message(&action.operation)));
        }
    }
    Ok(None)
}

fn mount_payload(module: &StudioIrModule) -> String {
    let tree = match module.screens.first() {
        Some(screen) => MountTree {
            protocol_version: PROTOCOL_VERSION,
            route: screen.route.clone(),
            root: ui_node(&screen.root),
        },
        // The parser admits documents whose only content is a script block;
        // they still have to mount a well-formed empty tree.
        None => MountTree {
            protocol_version: PROTOCOL_VERSION,
            route: "/".to_owned(),
            root: UiNode {
                id: "root".to_owned(),
                kind: NodeKind::Empty,
                props: BTreeMap::new(),
                children: Vec::new(),
            },
        },
    };
    let message = GuestMessage::Mount(tree);
    serde_json::to_string(&message).unwrap_or_else(|_| "{\"type\":\"mount\"}".to_owned())
}

fn ui_node(node: &IrNode) -> UiNode {
    match node {
        IrNode::Element(element) => UiNode {
            id: element.id.clone(),
            kind: node_kind(&element.kind),
            props: element
                .properties
                .iter()
                .map(|(name, property)| (name.clone(), property_value(property)))
                .collect(),
            children: element.children.iter().map(ui_node).collect(),
        },
        IrNode::Text(text) => {
            let mut props = BTreeMap::new();
            props.insert("text".to_owned(), Value::String(text.text.clone()));
            UiNode {
                id: text.id.clone(),
                kind: NodeKind::Text,
                props,
                children: Vec::new(),
            }
        }
    }
}

fn node_kind(kind: &str) -> NodeKind {
    // Lowering already admitted only catalog kinds; the fallback keeps the
    // emitter total without panicking on hand-built IR.
    serde_json::from_str::<NodeKind>(&format!("\"{kind}\""))
        .unwrap_or(NodeKind::Empty)
}

fn property_value(property: &IrProperty) -> Value {
    match property {
        IrProperty::String(value) => Value::String(value.clone()),
        IrProperty::Boolean(value) => Value::Bool(*value),
        IrProperty::Number(value) => number_value(value),
    }
}

fn number_value(canonical: &str) -> Value {
    if let Ok(value) = canonical.parse::<u64>() {
        return Value::from(value);
    }
    if let Ok(value) = canonical.parse::<i64>() {
        return Value::from(value);
    }
    canonical
        .parse::<f64>()
        .map(Value::from)
        .unwrap_or_else(|_| Value::String(canonical.to_owned()))
}

fn navigate_message(operation: &IrNavigationOperation) -> String {
    let command = match operation {
        IrNavigationOperation::Push { route } => NavigationCommand::Push {
            route: route.clone(),
        },
        IrNavigationOperation::Replace { route } => NavigationCommand::Replace {
            route: route.clone(),
        },
        IrNavigationOperation::PopTo { route } => NavigationCommand::PopTo {
            route: route.clone(),
        },
        IrNavigationOperation::Reset { route } => NavigationCommand::Reset {
            route: route.clone(),
        },
        IrNavigationOperation::Pop => NavigationCommand::Pop,
    };
    let message = GuestMessage::Navigate(command);
    serde_json::to_string(&message).unwrap_or_else(|_| "{\"type\":\"navigate\"}".to_owned())
}

fn escape_json(value: &str) -> String {
    value
        .chars()
        .flat_map(|character| {
            if character == '"' || character == '\\' {
                vec!['\\', character]
            } else {
                vec![character]
            }
        })
        .collect()
}

/// Escape one AssemblyScript double-quoted string literal body.
///
/// UNVERIFIED: control characters other than `\n`, `\r`, and `\t` are escaped
/// as four-digit `\uXXXX`; confirm the pinned AssemblyScript revision accepts
/// that form before relying on exotic prop strings.
fn escape_as_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character if character.is_control() => {
                let code = u32::from(character);
                escaped.push_str(&format!("\\u{code:04x}"));
            }
            character => escaped.push(character),
        }
    }
    escaped
}

#[cfg(test)]
mod tests {
    use super::{escape_as_string, escape_json};

    #[test]
    fn escapes_quotes_backslashes_and_newlines() {
        assert_eq!(escape_as_string("a\"b\\c\nd"), "a\\\"b\\\\c\\nd");
        assert_eq!(escape_json("say \"hi\""), "say \\\"hi\\\"");
    }
}
