//! The deterministic Studio IR → `AssemblyScript` lowering backend.
//!
//! [`emit`] renders one static guest module in the exact conventions of the
//! existing hand-written examples (`examples/starter`, `examples/pos-desktop`):
//! a `studio_init` export that emits a v1 protocol `mount` payload, and a
//! `studio_event` export that dispatches typed navigation actions.  The
//! emitted text is a pure function of the IR, so identical input produces
//! byte-identical output.
//!
//! Compilation from generated `AssemblyScript` to Wasm intentionally reuses the
//! example build machinery (`asc` + `asconfig.json`); this crate does not
//! invoke any compiler itself.
//!
//! # Intentionally non-deterministic seams
//!
//! None inside this crate.  Byte-for-byte determinism ends at the ASC toolchain
//! boundary, which is owned by the example/package build configuration.
//!
//! # Debug oracle
//!
//! [`simulate_event`] mirrors the dispatch the emitter generates, in pure Rust,
//! so tests can compare observable mount/navigate behavior against a
//! hand-written counterpart without executing Wasm.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use serde_json::Value;
use studio_protocol::{
    GuestMessage, HostEvent, MountTree, NavigationCommand, NodeKind, PROTOCOL_VERSION, UiNode,
};

use crate::ir::{
    ComponentDefinition, IrNavigationOperation, IrNode, IrProperty, Mutation, MutationOp,
    StudioExpression, StudioIrModule,
};
use crate::types::{StudioType, StudioValue};

/// The artifacts of one lowering: generated `AssemblyScript` plus the mount
/// payload it embeds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmittedModule {
    /// Generated `AssemblyScript` source text.
    pub assembly_source: String,
    /// The v1 protocol `mount` payload emitted by `studio_init`.
    pub mount_payload: String,
}

/// Emit deterministic `AssemblyScript` for a lowered module.
///
/// The first screen is mounted at startup; every navigation action becomes one
/// branch of the generated `studio_event` dispatch, in authored order.
#[must_use]
pub fn emit(module: &StudioIrModule) -> EmittedModule {
    let mount_payload = mount_payload(module);
    let mut source = String::new();
    source.push_str("// Generated by studio-script::assemblyscript. DO NOT EDIT.\n");
    let _ = writeln!(
        source,
        "// Studio IR version {}; {} screen(s); {} navigation action(s).",
        module.version,
        module.screens.len(),
        module.actions.len()
    );
    source.push_str("\nconst MOUNT_PAYLOAD: string = \"");
    source.push_str(&escape_as_string(&mount_payload));
    source.push_str("\";\n\n");

    source.push_str("@external(\"studio_host\", \"emit\")\n");
    source.push_str("declare function hostEmit(pointer: i32, length: i32): i32;\n\n");

    source.push_str("function emit(message: string): i32 {\n");
    source.push_str("  const bytes = String.UTF8.encode(message, false);\n");
    source.push_str("  return hostEmit(changetype<i32>(bytes), bytes.byteLength);\n");
    source.push_str("}\n\n");

    source.push_str("export function studio_alloc(length: i32): i32 {\n");
    source.push_str("  if (length < 0 || length > 65536) { return 0; }\n");
    source.push_str("  return heap.alloc(length > 0 ? length : 8) as i32;\n");
    source.push_str("}\n\n");
    source.push_str("export function studio_dealloc(_pointer: i32, _length: i32): void {}\n\n");

    source.push_str("export function studio_init(_pointer: i32, _length: i32): i32 {\n");
    source.push_str("  return emit(MOUNT_PAYLOAD);\n");
    source.push_str("}\n\n");

    source.push_str("export function studio_event(pointer: i32, length: i32): i32 {\n");
    source.push_str("  const event = String.UTF8.decodeUnsafe(pointer, length, false);\n");
    for action in &module.actions {
        let trigger = format!("\"node_id\":\"{}\"", escape_json(&action.trigger_node_id));
        let event_match = format!("\"event\":\"{}\"", action.trigger_event.as_str());
        let _ = writeln!(
            source,
            "  if (event.includes(\"{}\") && event.includes(\"{}\")) {{",
            escape_as_string(&trigger),
            escape_as_string(&event_match)
        );
        source.push_str("    return emit(\"");
        source.push_str(&escape_as_string(&navigate_message(&action.operation)));
        source.push_str("\");\n");
        source.push_str("  }\n");
    }
    source.push_str("  return 0;\n");
    source.push_str("}\n");

    EmittedModule {
        assembly_source: source,
        mount_payload,
    }
}

/// Mirror the generated `studio_event` dispatch in pure Rust.
///
/// Given a serialized [`HostEvent`] envelope, returns the serialized
/// [`GuestMessage`] the emitted module would respond with, or [`None`] when no
/// generated branch matches.
///
/// # Errors
///
/// Returns an error message when `event_json` is not a valid host UI event.
pub fn simulate_event(module: &StudioIrModule, event_json: &str) -> Result<Option<String>, String> {
    let Ok(HostEvent::Ui(event)) = serde_json::from_str::<HostEvent>(event_json) else {
        return Err("event_json is not a serialized host UI event".to_owned());
    };
    for action in &module.actions {
        if action.trigger_node_id == event.node_id && action.trigger_event.as_str() == event.event {
            return Ok(Some(navigate_message(&action.operation)));
        }
    }
    Ok(None)
}

fn mount_payload(module: &StudioIrModule) -> String {
    let tree = match module.screens.first() {
        Some(screen) => MountTree {
            protocol_version: PROTOCOL_VERSION,
            route: screen.route.clone(),
            root: ui_node(&screen.root),
        },
        // The parser admits documents whose only content is a script block;
        // they still have to mount a well-formed empty tree.
        None => MountTree {
            protocol_version: PROTOCOL_VERSION,
            route: "/".to_owned(),
            root: UiNode {
                id: "root".to_owned(),
                kind: NodeKind::Empty,
                props: BTreeMap::new(),
                children: Vec::new(),
            },
        },
    };
    let message = GuestMessage::Mount(tree);
    serde_json::to_string(&message).unwrap_or_else(|_| "{\"type\":\"mount\"}".to_owned())
}

fn ui_node(node: &IrNode) -> UiNode {
    match node {
        IrNode::Element(element) => UiNode {
            id: element.id.clone(),
            kind: node_kind(&element.kind),
            props: element
                .properties
                .iter()
                .map(|(name, property)| (name.clone(), property_value(property)))
                .collect(),
            children: element.children.iter().map(ui_node).collect(),
        },
        IrNode::Text(text) => {
            let mut props = BTreeMap::new();
            props.insert("text".to_owned(), Value::String(text.text.clone()));
            UiNode {
                id: text.id.clone(),
                kind: NodeKind::Text,
                props,
                children: Vec::new(),
            }
        }
    }
}

fn node_kind(kind: &str) -> NodeKind {
    // Lowering already admitted only catalog kinds; the fallback keeps the
    // emitter total without panicking on hand-built IR.
    serde_json::from_str::<NodeKind>(&format!("\"{kind}\"")).unwrap_or(NodeKind::Empty)
}

fn property_value(property: &IrProperty) -> Value {
    match property {
        IrProperty::String(value) => Value::String(value.clone()),
        IrProperty::Boolean(value) => Value::Bool(*value),
        IrProperty::Number(value) => number_value(value),
    }
}

fn number_value(canonical: &str) -> Value {
    if let Ok(value) = canonical.parse::<u64>() {
        return Value::from(value);
    }
    if let Ok(value) = canonical.parse::<i64>() {
        return Value::from(value);
    }
    canonical
        .parse::<f64>()
        .map_or_else(|_| Value::String(canonical.to_owned()), Value::from)
}

fn navigate_message(operation: &IrNavigationOperation) -> String {
    let command = match operation {
        IrNavigationOperation::Push { route } => NavigationCommand::Push {
            route: route.clone(),
        },
        IrNavigationOperation::Replace { route } => NavigationCommand::Replace {
            route: route.clone(),
        },
        IrNavigationOperation::PopTo { route } => NavigationCommand::PopTo {
            route: route.clone(),
        },
        IrNavigationOperation::Reset { route } => NavigationCommand::Reset {
            route: route.clone(),
        },
        IrNavigationOperation::Pop => NavigationCommand::Pop,
    };
    let message = GuestMessage::Navigate(command);
    serde_json::to_string(&message).unwrap_or_else(|_| "{\"type\":\"navigate\"}".to_owned())
}

fn escape_json(value: &str) -> String {
    value
        .chars()
        .flat_map(|character| {
            if character == '"' || character == '\\' {
                vec!['\\', character]
            } else {
                vec![character]
            }
        })
        .collect()
}

/// Escape one `AssemblyScript` double-quoted string literal body.
///
/// UNVERIFIED: control characters other than `\n`, `\r`, and `\t` are escaped
/// as four-digit `\uXXXX`; confirm the pinned `AssemblyScript` revision accepts
/// that form before relying on exotic prop strings.
fn escape_as_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character if character.is_control() => {
                let code = u32::from(character);
                let _ = write!(escaped, "\\u{code:04x}");
            }
            character => escaped.push(character),
        }
    }
    escaped
}

#[cfg(test)]
mod tests {
    use super::{escape_as_string, escape_json};

    #[test]
    fn escapes_quotes_backslashes_and_newlines() {
        assert_eq!(escape_as_string("a\"b\\c\nd"), "a\\\"b\\\\c\\nd");
        assert_eq!(escape_json("say \"hi\""), "say \\\"hi\\\"");
    }
}

/// Failure lowering a v2 Studio module to `AssemblyScript`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StudioEmitError {
    /// Stable code (`STUDIO340` for structural limits).
    pub code: &'static str,
    /// Safe message.
    pub message: String,
}

/// The artifacts of one v2 lowering: generated `AssemblyScript` plus the mount
/// payload it embeds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmittedStudio {
    /// Generated standalone `AssemblyScript` source text (no imports).
    pub assembly_source: String,
    /// The v1 protocol `mount` payload emitted by `studio_init`.
    pub mount_payload: String,
}

/// Emit deterministic standalone `AssemblyScript` for one v2 module.
///
/// The generated module mirrors the proven shape: a `MOUNT_PAYLOAD` constant,
/// the `studio_host.emit` extern, and `studio_init`/`studio_event`/
/// `studio_alloc` exports. Each handler becomes one dispatch branch returning
/// its canonical emission JSON. Payloads are mount-time constants because v2
/// has no state-mutation operations; when such operations arrive, this
/// backend must become dynamic (tracked by the IR version).
///
/// # Errors
///
/// Returns [`StudioEmitError`] for multi-component modules (which need the
/// module graph) and for projection failures.
pub fn emit_studio(module: &crate::ir::StudioModule) -> Result<EmittedStudio, StudioEmitError> {
    let [component] = module.components.as_slice() else {
        return Err(StudioEmitError {
            code: crate::CODE_MODULE_GRAPH,
            message: "multi-component modules need the module graph".to_owned(),
        });
    };
    let (tree, scope) =
        crate::eval::mount_tree(module, component, &std::collections::BTreeMap::new()).map_err(
            |error| StudioEmitError {
                code: crate::CODE_NO_LOWERING_RULE,
                message: error.message,
            },
        )?;
    let mount_payload = serde_json::to_string(&GuestMessage::Mount(tree))
        .unwrap_or_else(|_| "{\"type\":\"mount\"}".to_owned());
    let mut source = String::new();
    source.push_str("// Generated by studio-script::assemblyscript::emit_studio. DO NOT EDIT.\n");
    let _ = writeln!(
        source,
        "// Studio IR version {}; module {}; {} handler(s).",
        module.version,
        module.id,
        component.handlers.len()
    );
    source.push_str("\nconst MOUNT_PAYLOAD: string = \"");
    source.push_str(&escape_as_string(&mount_payload));
    source.push_str("\";\n\n");
    source.push_str(&stateful_prelude(component)?);

    source.push_str("@external(\"studio_host\", \"emit\")\n");
    source.push_str("declare function hostEmit(pointer: i32, length: i32): i32;\n\n");

    source.push_str("function emit(message: string): i32 {\n");
    source.push_str("  const bytes = String.UTF8.encode(message, false);\n");
    source.push_str("  return hostEmit(changetype<i32>(bytes), bytes.byteLength);\n");
    source.push_str("}\n\n");

    source.push_str("export function studio_alloc(length: i32): i32 {\n");
    source.push_str("  if (length < 0 || length > 65536) { return 0; }\n");
    source.push_str("  return heap.alloc(length > 0 ? length : 8) as i32;\n");
    source.push_str("}\n\n");

    source.push_str("export function studio_dealloc(_pointer: i32, _length: i32): void {}\n\n");

    source.push_str("export function studio_init(_pointer: i32, _length: i32): i32 {\n");
    source.push_str("  return emit(MOUNT_PAYLOAD);\n");
    source.push_str("}\n\n");

    source.push_str("export function studio_event(pointer: i32, length: i32): i32 {\n");
    source.push_str("  const event = String.UTF8.decodeUnsafe(pointer, length, false);\n");
    for handler in &component.handlers {
        let Some(node) = handler.node.as_deref() else {
            continue;
        };
        let trigger = format!("\"node_id\":\"{node}\"");
        let event_match = format!("\"event\":\"{}\"", handler.event);
        // UiEvent serializes node_id/event plainly; match the v1 convention.
        let _ = writeln!(
            source,
            "  if (event.includes(\"{}\") && event.includes(\"{}\")) {{",
            escape_as_string(&trigger),
            escape_as_string(&event_match),
        );
        for mutation in &handler.mutations {
            source.push_str("    ");
            source.push_str(&emit_mutation(component, mutation)?);
            source.push('\n');
        }
        source.push_str("    recomputeStudioDerived();\n");
        if handler.emit.is_empty() {
            source.push_str("    studioPatchSequence = studioPatchSequence + 1;\n");
            source.push_str("    return emit(");
            source.push_str(&emit_patch_expression(module, component)?);
            source.push_str(");\n");
        } else {
            let emission = crate::eval::dispatch_event(
                component,
                &scope,
                node,
                &handler.event,
                &component.handlers,
            )
            .map_err(|error| StudioEmitError {
                code: crate::CODE_NO_LOWERING_RULE,
                message: error.message,
            })?
            .ok_or_else(|| StudioEmitError {
                code: crate::CODE_NO_LOWERING_RULE,
                message: format!("handler for {node} stopped matching"),
            })?;
            source.push_str("    return emit(\"");
            source.push_str(&escape_as_string(&emission.to_json()));
            source.push_str("\");\n");
        }
        source.push_str("  }\n");
    }
    source.push_str("  return 0;\n");
    source.push_str("}\n");

    Ok(EmittedStudio {
        assembly_source: source,
        mount_payload,
    })
}

/// Value family relevant to code generation.
#[derive(Clone, Copy, PartialEq, Eq)]
enum ContentTy {
    String,
    Number,
    Boolean,
    /// Anything else (arrays, records, locals, calls): unsupported in
    /// generated interaction code.
    Other,
}

/// Row context for code inside dynamic list rows: parallel-array prefix,
/// item/index binding names, per-field families, and the index expression.
struct RowCtx<'a> {
    /// Array prefix, e.g. `each_cartlines`.
    prefix: String,
    /// Item binding name as written.
    item: String,
    /// Declared index binding name.
    index_name: String,
    /// ASC expression for the item position (`i` or a temp).
    index_expr: String,
    /// Field families for `item.<field>` reads.
    fields: &'a std::collections::BTreeMap<String, ContentTy>,
}

impl RowCtx<'_> {
    /// Resolve an item/index local read to an ASC expression plus family.
    fn resolve(&self, path: &str) -> Result<(String, ContentTy), StudioEmitError> {
        if path == self.item {
            // Matches `as_text` on records: renders empty.
            return Ok(("".to_owned(), ContentTy::String));
        }
        if path == self.index_name {
            return Ok((self.index_expr.clone(), ContentTy::Number));
        }
        if let Some(field) = path
            .strip_prefix(self.item.as_str())
            .and_then(|rest| rest.strip_prefix('.'))
        {
            if field.is_empty() || field.contains('.') {
                return Err(emit_failed("nested item reads"));
            }
            let Some(ty) = self.fields.get(field) else {
                return Err(emit_failed("unknown item fields"));
            };
            return Ok((format!("{}_{}[{}]", self.prefix, field, self.index_expr), *ty));
        }
        Err(emit_failed("unbound locals in rows"))
    }
}

/// Classify an expression for code generation against component bindings.
fn content_ty(
    component: &ComponentDefinition,
    row: Option<&RowCtx>,
    expression: &StudioExpression,
) -> ContentTy {
    match expression {
        StudioExpression::Literal(value) => match value {
            StudioValue::String(_) => ContentTy::String,
            StudioValue::Number(_) => ContentTy::Number,
            StudioValue::Boolean(_) => ContentTy::Boolean,
            StudioValue::Array(_) | StudioValue::Record(_) => ContentTy::Other,
        },
        StudioExpression::ReadState(name) => slot_ty(
            component
                .state
                .iter()
                .find(|slot| &slot.name == name)
                .map(|slot| &slot.ty),
        ),
        StudioExpression::ReadDerived(name) => slot_ty(
            component
                .derived
                .iter()
                .find(|slot| &slot.name == name)
                .map(|slot| &slot.ty),
        ),
        StudioExpression::ReadProp(name) => slot_ty(
            component
                .props
                .iter()
                .find(|prop| &prop.name == name)
                .map(|prop| &prop.ty),
        ),
        StudioExpression::ReadLocal(path) => row
            .and_then(|row| row.resolve(path).ok())
            .map_or(ContentTy::Other, |(_, ty)| ty),
        StudioExpression::Conditional { .. }
        | StudioExpression::Array(_)
        | StudioExpression::Record(_)
        | StudioExpression::CallApprovedFunction { .. } => ContentTy::Other,
        StudioExpression::Unary { operator, .. } => match operator.as_str() {
            "!" => ContentTy::Boolean,
            "-" | "+" => ContentTy::Number,
            _ => ContentTy::Other,
        },
        StudioExpression::Binary {
            operator,
            left,
            right,
        } => match operator.as_str() {
            "+" => {
                if content_ty(component, row, left) == ContentTy::String
                    || content_ty(component, row, right) == ContentTy::String
                {
                    ContentTy::String
                } else {
                    ContentTy::Number
                }
            }
            "-" | "*" | "/" | "%" => ContentTy::Number,
            "==" | "===" | "!=" | "!==" | "<" | ">" | "<=" | ">=" | "&&" | "||" => {
                ContentTy::Boolean
            }
            _ => ContentTy::Other,
        },
    }
}

fn slot_ty(ty: Option<&StudioType>) -> ContentTy {
    match ty {
        Some(StudioType::String) => ContentTy::String,
        Some(StudioType::Number) => ContentTy::Number,
        Some(StudioType::Boolean) => ContentTy::Boolean,
        _ => ContentTy::Other,
    }
}

fn emit_failed(what: &str) -> StudioEmitError {
    StudioEmitError {
        code: crate::CODE_NO_LOWERING_RULE,
        message: format!("{what} is not supported in generated interaction code"),
    }
}

/// `AssemblyScript` global name for a binding read.
fn binding_global(expression: &StudioExpression) -> Result<String, StudioEmitError> {
    match expression {
        StudioExpression::ReadState(name) => Ok(format!("state_{name}")),
        StudioExpression::ReadDerived(name) => Ok(format!("derived_{name}")),
        StudioExpression::ReadProp(name) => Ok(format!("prop_{name}")),
        _ => Err(emit_failed("non-binding reads")),
    }
}

/// Emit an expression as an `AssemblyScript` string expression.
fn emit_str_expr(
    component: &ComponentDefinition,
    row: Option<&RowCtx>,
    expression: &StudioExpression,
) -> Result<String, StudioEmitError> {
    if let (Some(row), StudioExpression::ReadLocal(path)) = (row, expression) {
        let (access, ty) = row.resolve(path)?;
        return match ty {
            ContentTy::String if access.is_empty() => Ok("\"\"".to_owned()),
            ContentTy::String => Ok(access),
            ContentTy::Number => Ok(format!("studioNumberToString({access})")),
            ContentTy::Boolean => Ok(format!("({access} ? \"true\" : \"false\")")),
            ContentTy::Other => Err(emit_failed("untyped row reads")),
        };
    }
    match expression {
        StudioExpression::Literal(StudioValue::String(text)) => {
            Ok(format!("\"{}\"", escape_as_string(text)))
        }
        StudioExpression::Literal(StudioValue::Number(_)) => Ok(format!(
            "studioNumberToString({})",
            emit_num_expr(component, row, expression)?
        )),
        StudioExpression::Literal(StudioValue::Boolean(_)) => Ok(format!(
            "({} ? \"true\" : \"false\")",
            emit_bool_expr(component, row, expression)?
        )),
        StudioExpression::Literal(StudioValue::Array(_) | StudioValue::Record(_)) => {
            Err(emit_failed("composite literals in text"))
        }
        _ if matches!(
            expression,
            StudioExpression::ReadState(_)
                | StudioExpression::ReadDerived(_)
                | StudioExpression::ReadProp(_)
        ) =>
        {
            match content_ty(component, row, expression) {
                ContentTy::String => binding_global(expression),
                ContentTy::Number => Ok(format!(
                    "studioNumberToString({})",
                    emit_num_expr(component, row, expression)?
                )),
                ContentTy::Boolean => Ok(format!(
                    "({} ? \"true\" : \"false\")",
                    emit_bool_expr(component, row, expression)?
                )),
                ContentTy::Other => Err(emit_failed("untyped binding reads")),
            }
        }
        StudioExpression::Binary { .. } => match content_ty(component, row, expression) {
            ContentTy::String => {
                let StudioExpression::Binary {
                    operator,
                    left,
                    right,
                } = expression
                else {
                    return Err(emit_failed("string concatenation"));
                };
                if operator != "+" {
                    return Err(emit_failed("non-concatenating text operators"));
                }
                Ok(format!(
                    "({} + {})",
                    emit_str_expr(component, row, left)?,
                    emit_str_expr(component, row, right)?
                ))
            }
            ContentTy::Number => Ok(format!(
                "studioNumberToString({})",
                emit_num_expr(component, row, expression)?
            )),
            ContentTy::Boolean => Ok(format!(
                "({} ? \"true\" : \"false\")",
                emit_bool_expr(component, row, expression)?
            )),
            ContentTy::Other => Err(emit_failed("untyped text expressions")),
        },
        _ => Err(emit_failed("complex text expressions")),
    }
}

/// Emit an expression as an `AssemblyScript` numeric expression.
fn emit_num_expr(
    component: &ComponentDefinition,
    row: Option<&RowCtx>,
    expression: &StudioExpression,
) -> Result<String, StudioEmitError> {
    if let (Some(row), StudioExpression::ReadLocal(path)) = (row, expression) {
        let (access, ty) = row.resolve(path)?;
        if ty == ContentTy::Number {
            return Ok(access);
        }
        return Err(emit_failed("non-numeric row reads in arithmetic"));
    }
    match expression {
        StudioExpression::Literal(StudioValue::Number(literal)) => Ok(literal.text.clone()),
        StudioExpression::Literal(_) => Err(emit_failed("non-numeric literals in arithmetic")),
        _ if matches!(
            expression,
            StudioExpression::ReadState(_)
                | StudioExpression::ReadDerived(_)
                | StudioExpression::ReadProp(_)
        ) =>
        {
            if content_ty(component, row, expression) == ContentTy::Number {
                binding_global(expression)
            } else {
                Err(emit_failed("non-numeric bindings in arithmetic"))
            }
        }
        StudioExpression::Binary {
            operator,
            left,
            right,
        } => match operator.as_str() {
            "+" | "-" | "*" | "/" | "%" => Ok(format!(
                "({} {} {})",
                emit_num_expr(component, row, left)?,
                operator,
                emit_num_expr(component, row, right)?
            )),
            _ => Err(emit_failed("non-arithmetic operators")),
        },
        StudioExpression::Unary { operator, operand } => match operator.as_str() {
            "-" | "+" => Ok(format!(
                "({}{})",
                operator,
                emit_num_expr(component, row, operand)?
            )),
            _ => Err(emit_failed("boolean negation in arithmetic")),
        },
        _ => Err(emit_failed("complex numeric expressions")),
    }
}

/// Emit an expression as an `AssemblyScript` boolean expression.
fn emit_bool_expr(
    component: &ComponentDefinition,
    row: Option<&RowCtx>,
    expression: &StudioExpression,
) -> Result<String, StudioEmitError> {
    if let (Some(row), StudioExpression::ReadLocal(path)) = (row, expression) {
        let (access, ty) = row.resolve(path)?;
        if ty == ContentTy::Boolean {
            return Ok(access);
        }
        return Err(emit_failed("non-boolean row reads in conditions"));
    }
    match expression {
        StudioExpression::Literal(StudioValue::Boolean(value)) => Ok(value.to_string()),
        StudioExpression::Literal(_) => Err(emit_failed("non-boolean literals in conditions")),
        _ if matches!(
            expression,
            StudioExpression::ReadState(_)
                | StudioExpression::ReadDerived(_)
                | StudioExpression::ReadProp(_)
        ) =>
        {
            if content_ty(component, row, expression) == ContentTy::Boolean {
                binding_global(expression)
            } else {
                Err(emit_failed("non-boolean bindings in conditions"))
            }
        }
        StudioExpression::Binary {
            operator,
            left,
            right,
        } => match operator.as_str() {
            "==" | "===" => Ok(format!(
                "({} == {})",
                emit_num_expr(component, row, left)?,
                emit_num_expr(component, row, right)?
            )),
            "!=" | "!==" => Ok(format!(
                "({} != {})",
                emit_num_expr(component, row, left)?,
                emit_num_expr(component, row, right)?
            )),
            "<" | ">" | "<=" | ">=" => Ok(format!(
                "({} {} {})",
                emit_num_expr(component, row, left)?,
                operator,
                emit_num_expr(component, row, right)?
            )),
            "&&" | "||" => Ok(format!(
                "({} {} {})",
                emit_bool_expr(component, row, left)?,
                operator,
                emit_bool_expr(component, row, right)?
            )),
            _ => Err(emit_failed("arithmetic in conditions")),
        },
        StudioExpression::Unary { operator, operand } => match operator.as_str() {
            "!" => Ok(format!("(!{})", emit_bool_expr(component, row, operand)?)),
            _ => Err(emit_failed("numeric negation in conditions")),
        },
        _ => Err(emit_failed("complex conditions")),
    }
}

/// Emit one state mutation statement.
fn emit_mutation(
    component: &ComponentDefinition,
    mutation: &Mutation,
) -> Result<String, StudioEmitError> {
    let Some(slot) = component
        .state
        .iter()
        .find(|slot| slot.name == mutation.slot)
    else {
        return Err(emit_failed("mutations of unknown slots"));
    };
    let target = format!("state_{}", slot.name);
    let slot_ty = slot_ty(Some(&slot.ty));
    let operand_ty = if matches!(mutation.op, MutationOp::Inc | MutationOp::Dec) {
        ContentTy::Number
    } else {
        content_ty(component, None, &mutation.operand)
    };
    match (mutation.op, slot_ty, operand_ty) {
        (MutationOp::Assign, slot_ty, operand_ty) if slot_ty == operand_ty => Ok(format!(
            "{target} = {};",
            emit_typed(component, None, &mutation.operand, slot_ty)?
        )),
        (MutationOp::Add | MutationOp::Sub, ContentTy::Number, ContentTy::Number) => {
            let operator = if mutation.op == MutationOp::Add {
                "+"
            } else {
                "-"
            };
            Ok(format!(
                "{target} = {target} {operator} {};",
                emit_num_expr(component, None, &mutation.operand)?
            ))
        }
        (MutationOp::Add, ContentTy::String, _) => Ok(format!(
            "{target} = {target} + {};",
            emit_str_expr(component, None, &mutation.operand)?
        )),
        (MutationOp::Inc | MutationOp::Dec, ContentTy::Number, _) => {
            let operator = if mutation.op == MutationOp::Inc {
                "+"
            } else {
                "-"
            };
            Ok(format!("{target} = {target} {operator} 1;"))
        }
        _ => Err(emit_failed("type-changing mutations")),
    }
}

/// Emit a value expression already known to have the given family.
fn emit_typed(
    component: &ComponentDefinition,
    row: Option<&RowCtx>,
    expression: &StudioExpression,
    ty: ContentTy,
) -> Result<String, StudioEmitError> {
    match ty {
        ContentTy::String => emit_str_expr(component, row, expression),
        ContentTy::Number => emit_num_expr(component, row, expression),
        ContentTy::Boolean => emit_bool_expr(component, row, expression),
        ContentTy::Other => Err(emit_failed("untyped values")),
    }
}

/// Emit the `AssemblyScript` expression evaluating to the patch envelope JSON.
///
/// Static JSON fragments embed through [`escape_as_string`]; value
/// expressions stay raw code. Every interpolated id/prop is JSON-encoded
/// first so quotes can never terminate the surrounding string literal.
fn emit_patch_expression(
    module: &crate::ir::StudioModule,
    component: &ComponentDefinition,
) -> Result<String, StudioEmitError> {
    let _ = module;
    let mut operations = asc_string_literal("[");
    let mut first = true;
    for binding in &component.content {
        let node = escape_as_string(
            &serde_json::to_string(&binding.node_id).map_err(|_| emit_failed("node ids"))?,
        );
        let property = escape_as_string(
            &serde_json::to_string(&binding.prop).map_err(|_| emit_failed("prop names"))?,
        );
        // Content props share text semantics: the value renders as a
        // JSON string built from the evaluated expression.
        let text = emit_str_expr(component, None, &binding.expression)?;
        let value = format!("\"\\\"\" + studioEscapeJson({text}) + \"\\\"\"");
        if !first {
            operations.push_str(" + \",\"");
        }
        first = false;
        let _ = write!(
            operations,
            " + \"{{\\\"op\\\":\\\"update_prop\\\",\\\"node_id\\\":{node},\\\"property\\\":{property},\\\"value\\\":\" + ({value}) + \"}}\""
        );
    }
    operations.push_str(" + \"]\"");
    Ok(format!(
        "{prefix} + studioPatchSequence.toString() + {middle} + {operations} + {suffix}",
        prefix = asc_string_literal("{\"type\":\"patch\",\"payload\":{\"sequence\":"),
        middle = asc_string_literal(",\"operations\":"),
        suffix = asc_string_literal("}}"),
    ))
}

/// One JSON document as an `AssemblyScript` string literal.
fn asc_string_literal(json: &str) -> String {
    format!("\"{}\"", escape_as_string(json))
}

/// Stateful prelude: binding globals, the patch sequence, the JSON string
/// escaper, and derived recomputation.
fn stateful_prelude(component: &ComponentDefinition) -> Result<String, StudioEmitError> {
    let mut prelude = String::new();
    for prop in &component.props {
        // Globals are zero-initialized; required props without defaults read
        // empty until a host-supplied value path arrives (future work).
        // Composite defaults have no scalar global form; content inside
        // iteration scopes is structural and never patched.
        if let Some(default) = prop.default.as_ref()
            && matches!(
                default,
                StudioValue::String(_) | StudioValue::Number(_) | StudioValue::Boolean(_)
            )
        {
            let _ = writeln!(
                prelude,
                "let prop_{} = {};",
                prop.name,
                initial_literal(default)?
            );
            continue;
        }
        if prop.default.is_none() {
            let _ = writeln!(
                prelude,
                "let prop_{}: {};",
                prop.name,
                ts_type(slot_ty(Some(&prop.ty)))
            );
        }
    }
    for slot in &component.state {
        let initial = slot_initial_value(slot)?;
        if !matches!(
            initial,
            StudioValue::String(_) | StudioValue::Number(_) | StudioValue::Boolean(_)
        ) {
            continue;
        }
        let _ = writeln!(
            prelude,
            "let state_{} = {};",
            slot.name,
            initial_literal(&initial)?
        );
    }
    for slot in &component.derived {
        let _ = writeln!(
            prelude,
            "let derived_{}: {} = {};",
            slot.name,
            ts_type(slot_ty(Some(&slot.ty))),
            ts_default(slot_ty(Some(&slot.ty)))
        );
    }
    prelude.push_str("let studioPatchSequence: i32 = 0;\n");
    prelude.push_str(
        "function studioEscapeJson(value: string): string {\n  let out = \"\";\n  for (let i = 0; i < value.length; i++) {\n    const code = value.charCodeAt(i);\n    if (code == 34) { out += \"\\\\\\\"\"; }\n    else if (code == 92) { out += \"\\\\\\\\\"; }\n    else if (code == 10) { out += \"\\\\n\"; }\n    else if (code == 13) { out += \"\\\\r\"; }\n    else if (code == 9) { out += \"\\\\t\"; }\n    else { out += String.fromCharCode(code); }\n  }\n  return out;\n}\n",
    );
    prelude.push_str("function studioNumberToString(value: f64): string {\n  if (isFinite(value) && value == Math.floor(value) && value > -9007199254740992.0 && value < 9007199254740992.0) {\n    return (value as i64).toString();\n  }\n  return value.toString();\n}\n");
    prelude.push_str("function recomputeStudioDerived(): void {\n");
    for slot in &component.derived {
        let _ = writeln!(
            prelude,
            "  derived_{} = {};",
            slot.name,
            emit_typed(component, None, &slot.expression, slot_ty(Some(&slot.ty)))?
        );
    }
    prelude.push_str("}\n");
    Ok(prelude)
}

/// Initial value of a state slot as a literal (initializers are literals).
fn slot_initial_value(
    slot: &crate::ir::StateSlot,
) -> Result<crate::types::StudioValue, StudioEmitError> {
    match &slot.initial {
        StudioExpression::Literal(value) => Ok(value.clone()),
        _ => Err(emit_failed("non-literal state initializers")),
    }
}

/// A value literal as `AssemblyScript` source.
fn initial_literal(value: &crate::types::StudioValue) -> Result<String, StudioEmitError> {
    match value {
        StudioValue::String(text) => Ok(format!("\"{}\"", escape_as_string(text))),
        StudioValue::Number(literal) => Ok(literal.text.clone()),
        StudioValue::Boolean(value) => Ok(value.to_string()),
        StudioValue::Array(_) | StudioValue::Record(_) => Err(emit_failed("composite globals")),
    }
}

/// `AssemblyScript` type for a value family.
fn ts_type(ty: ContentTy) -> &'static str {
    match ty {
        ContentTy::Number => "f64",
        ContentTy::Boolean => "bool",
        ContentTy::String | ContentTy::Other => "string",
    }
}

/// Zero value for a family (overwritten before any read).
fn ts_default(ty: ContentTy) -> &'static str {
    match ty {
        ContentTy::Number => "0",
        ContentTy::Boolean => "false",
        ContentTy::String | ContentTy::Other => "\"\"",
    }
}

/// One dynamic row list: everything row code generation needs.
struct BlockPlan<'a> {
    /// Template `Each` node id.
    id: String,
    /// Wrapper node id (`{id}#items`).
    wrapper: String,
    /// ASC identifier prefix (`each_<sanitized>`).
    prefix: String,
    /// Iterated state slot.
    slot: String,
    /// Item binding name.
    item: String,
    /// Index binding name.
    index_name: String,
    /// Key expression.
    key: &'a StudioExpression,
    /// Row template roots.
    body: &'a [crate::ir::TemplateNode],
    /// Empty-collection template roots.
    fallback: &'a [crate::ir::TemplateNode],
    /// Used fields in first-seen order with families.
    fields: Vec<(String, ContentTy)>,
}

/// Sanitize a node id into an ASC identifier fragment.
fn sanitize_id(id: &str) -> String {
    id.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect()
}

/// Collect dynamic row lists: `Each` blocks iterating a state slot that
/// any handler mutates with a list operation.
fn collect_blocks<'a>(
    component: &'a ComponentDefinition,
) -> Result<Vec<BlockPlan<'a>>, StudioEmitError> {
    let mut mutated: Vec<&str> = Vec::new();
    for handler in &component.handlers {
        for mutation in &handler.mutations {
            if matches!(
                mutation.op,
                crate::ir::MutationOp::Push
                    | crate::ir::MutationOp::Pop
                    | crate::ir::MutationOp::Remove
                    | crate::ir::MutationOp::Clear
            ) && !mutated.contains(&mutation.slot.as_str())
            {
                mutated.push(mutation.slot.as_str());
            }
        }
    }
    let mut blocks = Vec::new();
    let mut stack: Vec<&'a crate::ir::TemplateNode> = component.template.iter().collect();
    while let Some(node) = stack.pop() {
        match node {
            crate::ir::TemplateNode::Each {
                id,
                collection,
                item,
                index,
                key,
                body,
                fallback,
                ..
            } => {
                let StudioExpression::ReadState(slot) = collection else {
                    continue;
                };
                if !mutated.contains(&slot.as_str()) {
                    continue;
                }
                let mut fields: Vec<(String, ContentTy)> = Vec::new();
                collect_row_reads(body, item, &mut fields, component)?;
                collect_row_reads(std::slice::from_ref(key), item, &mut fields, component)?;
                blocks.push(BlockPlan {
                    wrapper: format!("{id}#items"),
                    prefix: format!("each_{}", sanitize_id(id)),
                    slot: slot.clone(),
                    item: item.clone(),
                    index_name: index.clone().unwrap_or_else(|| "index".to_owned()),
                    key,
                    body,
                    fallback,
                    fields,
                    id: id.clone(),
                });
            }
            crate::ir::TemplateNode::Component { children, .. } => {
                stack.extend(children.iter());
            }
            crate::ir::TemplateNode::If {
                consequent,
                alternate,
                ..
            } => {
                stack.extend(consequent.iter().chain(alternate.iter()));
            }
            crate::ir::TemplateNode::Text { .. } | crate::ir::TemplateNode::Interpolation { .. } => {
            }
        }
    }
    blocks.sort_by(|left, right| left.wrapper.cmp(&right.wrapper));
    Ok(blocks)
}

/// Collect `item.<field>` read names for parallel arrays.
fn collect_row_reads(
    nodes: &[crate::ir::TemplateNode],
    item: &str,
    fields: &mut Vec<String>,
) {
    let mut stack: Vec<&crate::ir::TemplateNode> = nodes.iter().collect();
    while let Some(node) = stack.pop() {
        match node {
            crate::ir::TemplateNode::Component {
                props, children, ..
            } => {
                for binding in props {
                    if let crate::ir::PropValue::Expression(expression) = &binding.value {
                        collect_expression_reads(expression, item, fields);
                    }
                }
                stack.extend(children.iter());
            }
            crate::ir::TemplateNode::Text { .. } => {}
            crate::ir::TemplateNode::Interpolation { expression, .. } => {
                collect_expression_reads(std::slice::from_ref(expression), item, fields);
            }
            crate::ir::TemplateNode::If { .. } | crate::ir::TemplateNode::Each { .. } => {}
        }
    }
}

/// Collect `item.<field>` read names from one expression.
fn collect_expression_reads(
    expression: &StudioExpression,
    item: &str,
    fields: &mut Vec<String>,
) {
    match expression {
        StudioExpression::ReadLocal(path) => {
            if path == item {
                return;
            }
            if let Some(field) = path
                .strip_prefix(item)
                .and_then(|rest| rest.strip_prefix('.'))
            {
                if !field.is_empty()
                    && !field.contains('.')
                    && !fields.iter().any(|known| known == field)
                {
                    fields.push(field.to_owned());
                }
            }
        }
        StudioExpression::Literal(_)
        | StudioExpression::ReadState(_)
        | StudioExpression::ReadDerived(_)
        | StudioExpression::ReadProp(_) => {}
        StudioExpression::Unary { operand, .. } => {
            collect_expression_reads(operand, item, fields);
        }
        StudioExpression::Binary { left, right, .. } => {
            collect_expression_reads(left, item, fields);
            collect_expression_reads(right, item, fields);
        }
        StudioExpression::Conditional {
            condition,
            consequent,
            alternate,
        } => {
            collect_expression_reads(condition, item, fields);
            collect_expression_reads(consequent, item, fields);
            collect_expression_reads(alternate, item, fields);
        }
        StudioExpression::Array(elements) => {
            for element in elements {
                collect_expression_reads(element, item, fields);
            }
        }
        StudioExpression::Record(entries) => {
            for (_, value) in entries {
                collect_expression_reads(value, item, fields);
            }
        }
        StudioExpression::CallApprovedFunction { arguments, .. } => {
            for argument in arguments {
                collect_expression_reads(argument, item, fields);
            }
        }
    }
}

/// Resolve field families from literal evidence: initial elements plus
/// push record literals across all handlers. Every read field needs a
/// literal type, and all evidence must agree.
fn resolve_field_types(
    component: &ComponentDefinition,
    slot: &str,
    reads: &[String],
) -> Result<std::collections::BTreeMap<String, ContentTy>, StudioEmitError> {
    let mut types: std::collections::BTreeMap<String, ContentTy> = Default::default();
    let mut observe = |field: &str, ty: ContentTy| -> Result<(), StudioEmitError> {
        match types.get(field) {
            Some(known) if *known != ty => Err(emit_failed("item fields changing type")),
            Some(_) => Ok(()),
            None => {
                types.insert(field.to_owned(), ty);
                Ok(())
            }
        }
    };
    if let Some(state) = component
        .state
        .iter()
        .find(|state| state.name == *slot)
    {
        if let StudioExpression::Literal(StudioValue::Array(elements)) = &state.initial {
            for element in elements {
                if let StudioValue::Record(fields) = element {
                    for (field, value) in fields {
                        observe(
                            field,
                            match value {
                                StudioValue::String(_) => ContentTy::String,
                                StudioValue::Number(_) => ContentTy::Number,
                                StudioValue::Boolean(_) => ContentTy::Boolean,
                                StudioValue::Array(_) | StudioValue::Record(_) => {
                                    return Err(emit_failed("nested item fields"));
                                }
                            },
                        )?;
                    }
                }
            }
        }
    }
    for handler in &component.handlers {
        for mutation in &handler.mutations {
            if mutation.op != crate::ir::MutationOp::Push || mutation.slot != slot {
                continue;
            }
            let StudioExpression::Record(entries) = &mutation.operand else {
                return Err(emit_failed("non-literal push operands"));
            };
            for (field, value) in entries {
                let ty = match literal_family(value) {
                    Ok(ty) => ty,
                    Err(_) => match content_ty(component, None, value) {
                        ContentTy::String | ContentTy::Number | ContentTy::Boolean => {
                            content_ty(component, None, value)
                        }
                        ContentTy::Other => {
                            return Err(emit_failed("untyped push fields"));
                        }
                    },
                };
                observe(field, ty)?;
            }
        }
    }
    for field in reads {
        if !types.contains_key(field) {
            return Err(emit_failed("item fields without literal evidence"));
        }
    }
    Ok(types)
}

/// Family of a literal value expression, if it is one.
fn literal_family(expression: &StudioExpression) -> Result<ContentTy, StudioEmitError> {
    match expression {
        StudioExpression::Literal(StudioValue::String(_)) => Ok(ContentTy::String),
        StudioExpression::Literal(StudioValue::Number(_)) => Ok(ContentTy::Number),
        StudioExpression::Literal(StudioValue::Boolean(_)) => Ok(ContentTy::Boolean),
        _ => Err(emit_failed("non-literal item fields")),
    }
}

/// Sanitize a node id into an ASC identifier fragment.
fn sanitize_id(id: &str) -> String {
    id.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect()
}

/// Collect dynamic row lists: `Each` blocks iterating a state slot that
/// any handler mutates with a list operation.
fn collect_blocks<'a>(
    component: &'a ComponentDefinition,
) -> Result<Vec<BlockPlan<'a>>, StudioEmitError> {
    let mut mutated: Vec<&str> = Vec::new();
    for handler in &component.handlers {
        for mutation in &handler.mutations {
            if matches!(
                mutation.op,
                crate::ir::MutationOp::Push
                    | crate::ir::MutationOp::Pop
                    | crate::ir::MutationOp::Remove
                    | crate::ir::MutationOp::Clear
            ) && !mutated.contains(&mutation.slot.as_str())
            {
                mutated.push(mutation.slot.as_str());
            }
        }
    }
    let mut blocks = Vec::new();
    let mut stack: Vec<&'a crate::ir::TemplateNode> = component.template.iter().collect();
    while let Some(node) = stack.pop() {
        match node {
            crate::ir::TemplateNode::Each {
                id,
                collection,
                item,
                index,
                key,
                body,
                fallback,
                ..
            } => {
                let StudioExpression::ReadState(slot) = collection else {
                    continue;
                };
                if !mutated.contains(&slot.as_str()) {
                    continue;
                }
                let mut fields: Vec<(String, ContentTy)> = Vec::new();
                collect_row_reads(body, item, &mut fields, component)?;
                collect_row_reads(std::slice::from_ref(key), item, &mut fields, component)?;
                blocks.push(BlockPlan {
                    wrapper: format!("{id}#items"),
                    prefix: format!("each_{}", sanitize_id(id)),
                    slot: slot.clone(),
                    item: item.clone(),
                    index_name: index.clone().unwrap_or_else(|| "index".to_owned()),
                    key,
                    body,
                    fallback,
                    fields,
                    id: id.clone(),
                });
            }
            crate::ir::TemplateNode::Component { children, .. } => {
                stack.extend(children.iter());
            }
            crate::ir::TemplateNode::If {
                consequent,
                alternate,
                ..
            } => {
                stack.extend(consequent.iter().chain(alternate.iter()));
            }
            crate::ir::TemplateNode::Text { .. } | crate::ir::TemplateNode::Interpolation { .. } => {
            }
        }
    }
    blocks.sort_by(|left, right| left.wrapper.cmp(&right.wrapper));
    Ok(blocks)
}

/// Collect `item.<field>` reads with families for parallel arrays.
fn collect_row_reads(
    nodes: &[crate::ir::TemplateNode],
    item: &str,
    fields: &mut Vec<(String, ContentTy)>,
    component: &ComponentDefinition,
) -> Result<(), StudioEmitError> {
    let mut stack: Vec<&crate::ir::TemplateNode> = nodes.iter().collect();
    while let Some(node) = stack.pop() {
        match node {
            crate::ir::TemplateNode::Component {
                props, children, ..
            } => {
                for binding in props {
                    if let crate::ir::PropValue::Expression(expression) = &binding.value {
                        collect_expression_reads(expression, item, fields, component)?;
                    }
                }
                stack.extend(children.iter());
            }
            crate::ir::TemplateNode::Text { .. } => {}
            crate::ir::TemplateNode::Interpolation { expression, .. } => {
                collect_expression_reads(std::slice::from_ref(expression), item, fields, component)?;
            }
            crate::ir::TemplateNode::If { .. } | crate::ir::TemplateNode::Each { .. } => {
                return Err(emit_failed("nested blocks in patched rows"));
            }
        }
    }
    Ok(())
}

/// Collect `item.<field>` reads from one expression.
fn collect_expression_reads(
    expression: &StudioExpression,
    item: &str,
    fields: &mut Vec<(String, ContentTy)>,
    component: &ComponentDefinition,
) -> Result<(), StudioEmitError> {
    match expression {
        StudioExpression::ReadLocal(path) => {
            if path == item {
                return Ok(());
            }
            if let Some(field) = path
                .strip_prefix(item)
                .and_then(|rest| rest.strip_prefix('.'))
            {
                if field.is_empty() || field.contains('.') {
                    return Err(emit_failed("nested item reads"));
                }
                let ty = match content_ty(component, None, expression) {
                    ContentTy::String | ContentTy::Number | ContentTy::Boolean => {
                        content_ty(component, None, expression)
                    }
                    ContentTy::Other => return Err(emit_failed("untyped item reads")),
                };
                if let Some(existing) = fields.iter().find(|(name, _)| name == field) {
                    if existing.1 != ty {
                        return Err(emit_failed("item fields changing type"));
                    }
                } else {
                    fields.push((field.to_owned(), ty));
                }
                return Ok(());
            }
            return Err(emit_failed("unbound locals in rows"));
        }
        StudioExpression::Literal(_)
        | StudioExpression::ReadState(_)
        | StudioExpression::ReadDerived(_)
        | StudioExpression::ReadProp(_) => Ok(()),
        StudioExpression::Unary { operand, .. } => {
            collect_expression_reads(operand, item, fields, component)
        }
        StudioExpression::Binary { left, right, .. } => {
            collect_expression_reads(left, item, fields, component)?;
            collect_expression_reads(right, item, fields, component)
        }
        StudioExpression::Conditional {
            condition,
            consequent,
            alternate,
        } => {
            collect_expression_reads(condition, item, fields, component)?;
            collect_expression_reads(consequent, item, fields, component)?;
            collect_expression_reads(alternate, item, fields, component)
        }
        StudioExpression::Array(elements) => elements
            .iter()
            .try_for_each(|element| collect_expression_reads(element, item, fields, component)),
        StudioExpression::Record(entries) => entries
            .iter()
            .try_for_each(|(_, value)| collect_expression_reads(value, item, fields, component)),
        StudioExpression::CallApprovedFunction { arguments, .. } => arguments
            .iter()
            .try_for_each(|argument| collect_expression_reads(argument, item, fields, component)),
    }
}
